name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore Erasmus_SSC/Erasmus_SSC/Erasmus_SSC.csproj

      - name: Build project
        run: dotnet build Erasmus_SSC/Erasmus_SSC/Erasmus_SSC.csproj --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish Erasmus_SSC/Erasmus_SSC/Erasmus_SSC.csproj --configuration Release --no-build

  deploy:

    needs: build

    runs-on: ubuntu-latest

    steps:

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            set -e

            echo "Moving to project..."
            cd ~/DoD

            echo "Pull latest code..."
            git pull origin main

            echo "Rebuilding containers..."
            docker compose up --build -d

            echo "Removing old images..."
            docker image prune -f

            echo "Running containers:"
            docker ps